# Generated by Django 4.2.1 on 2023-05-04 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="empresa_email",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="empresa_telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="credito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credito_dt_aquisicao", models.DateTimeField(auto_now_add=True)),
                ("credito_dt_uso", models.DateTimeField()),
                (
                    "credito_valor_pago",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "credito_adquirido",
                    models.DecimalField(decimal_places=1, max_digits=10),
                ),
                ("credito_usado", models.DecimalField(decimal_places=1, max_digits=10)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
            ],
        ),
    ]
