# Generated by Django 4.2.1 on 2023-05-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_empresa_empresa_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credito",
            name="credito_dt_uso",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credito",
            name="credito_usado",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
