# Generated by Django 4.2.1 on 2023-05-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_credito_credito_dt_uso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credito",
            name="credito_dt_vencimento",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
