# Generated by Django 4.2.1 on 2023-05-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_credito_credito_dt_vencimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credito",
            name="credito_dt_uso",
        ),
    ]
