# Generated by Django 4.2.1 on 2023-05-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_credito_credito_dt_uso"),
    ]

    operations = [
        migrations.AddField(
            model_name="credito",
            name="credito_dt_uso",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
