# Generated by Django 4.2.1 on 2023-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_empresa_credito_empresa_compradora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="empresa_creditos",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
