# Generated by Django 4.2.1 on 2023-05-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_empresa_creditos_empresa_empresa_saldo_creditos"),
    ]

    operations = [
        migrations.AddField(
            model_name="credito",
            name="credito_parcialmente_finalizado",
            field=models.BooleanField(default=False),
        ),
    ]
