# Generated by Django 4.2.1 on 2023-05-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_credito_credito_parcialmente_finalizado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credito_usado",
            name="empresa_debitada",
        ),
    ]
