# Generated by Django 4.2.1 on 2023-05-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_workbox_w_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito_usado',
            name='empresa_creditada',
        ),
    ]
